language: node_js
node_js:
- stable
sudo: false
script:
- npm install
- npm test
deploy:
  provider: npm
  email: p.krautzberger@gmail.com
  api_key:
    secure: fjw+oIBtlqUx0sPAv0YcioWtin42OSbB+qDsqEs4i6Tw+pXtheChhuMhcGg4BhAAG/8qFKypy2FXb0X6s+mzCrPmOd0XjobnGCY07hHB31/x25tlUOmE/d4BvFiPYSBM26eCTwOiwGQcocedonivM4z3LwL36u+IEM/Zg68EOtXJDYF33ULpgVNBvT54dhSNglrX3q+XfkaYgMPz5z9QWWhwBJWii7vHdlblFy46PYE0FFA7ZtNA8KLIO6yj00pFLheD0DXPTwtK4TfK1H1tun+vU1Jhj3eLzyYQZ7Sa4RI3RWLvPYGx7Wbh5FPq4BfCm0VHfcy4ey7n9FdXN2aax/4dedgwgOGXUVEfAipSdDHXIPWsN8jefC9HkhfN2/qiu08rp7uz0eJ23/Q/7CzQ81hhoCmj+dWL8d5N20FuaRnnLszlVkW/i40FDQYgCW6DMHNj8LuU3WUqfDDcvZzMigA7llEkLZtnONh3Zb66Bj6iusjzJD2APTPS6/EPYzFBVXfYqm3Wb37XqP1MFFoX7j6OiKQVzcKGLTsNPPMECl20OZ/eyREglHFCCTfTeI6wIw+3Qy74mRlIZg1g743lsOk3lQvWR6W2J3xs0zOEDP5qHcSGPtqH+rgE67xg/UkTc09xVPXfhfOKRSIp0vUt9DB2CqKD+R/Uilws1JH8ILA=
  on:
    tags: true
    repo: pkra/mathjax-node-sre
